### PR TITLE
Change definition of Atomics module

### PR DESCRIPTION
**Pull request by lyricsboy**
Creating a PR to host discussion.

### CODE REVIEW

**Comment by lyricsboy** [comment]
I tested this locally and see the same result as Travis:

> Carthage/Build/iOS/Deferred.framework/Modules/module.private.modulemap:1:8: Redefinition of module 'Atomics'

**Comment by zwaldowski** [comment]
Pushed more changes, seeing what Travis things. Give it a shot.

**Comment by lyricsboy** [comment]
This builds locally for me, which is good news. I have submitted it to Jenkins on our side. It'll be a race to see who wins between Travis here and Jenkins there.

**Comment by lyricsboy** [comment]
Our jobs succeeded with carthage_cache built from 7a660a10ddb61f089955f70332ed53d9cfee7217. I'll test it again with the new HEAD here.

**Comment by lyricsboy** [comment]
At least one job has succeeded on 4578512 now, so I think this is good!

**Pull request merged**
