### PR TITLE
Apply Swift 3 API Guidelines

### PR DESCRIPTION
**Pull request by zwaldowski**
#### What's in this pull request?

See #101. Addresses #66.

#### Testing

Few changes that effect testing; mostly a lateral naming change.

#### API Changes

Break-the-world change.

### CODE REVIEW

**Comment by piercifani** [comment]
I cannot seem to compile this for iOS or macOS: the import for [this module](https://github.com/bignerdranch/Deferred/blob/zwaldowski/swift-3_0/naming/Sources/Deferred/Deferred.swift#L10) looks like it's not defined

**Comment by zwaldowski** [comment]
@piercifani: Our CI builds are passing, and this builds on my local machine in Xcode and SwiftPM. Can I get a build log?

**Comment by piercifani** [comment]
Sure! I can send you a example project, find it [here](https://github.com/piercifani/TestDeferred)

Just check it out, open the workspace, try to build, and you'll see this: https://i.imgur.com/m4yESFG.png

**Comment by zwaldowski** [comment]
@piercifani: Ah! You didn't mention CocoaPods. I made a mistake in the spec. I've pushed to both branches addressing the problem.

**Comment by piercifani** [comment]
@zwaldowski thansk! that did it

**Pull request merged**
