### PR TITLE
Fix deinit races

### PR DESCRIPTION
**Pull request by zwaldowski**
#### What's in this pull request?

Lots of fixes for #144 and friends.

#### Testing

@piercifani has submitted a sample of code as a full-stack test suite. We loop this 20 times to allow as a smoke test for deallocation problems.

#### API Changes

`Task` gains `isCancelled`.

### CODE REVIEW

**Comment by piercifani** [comment]
Regarding the test: in my latest gist [I filled](https://gist.github.com/piercifani/5c82f349300ab28272dbd8b2e1953548#file-allsuccededcrash-swift-L67) the deferred in `sync(file:)` in a different GCD queue for each file and that enhanced the possibility of the race condition occurring and the app crashing.

Can we include that change so the smoke test is more reliable?

Thanks!

**Comment by piercifani** [comment]
Looks like it works, tested on an iPad Air 2 on release mode and no issue found yet.

Great job! 👍

**Comment by zwaldowski** [comment]
@piercifani Hooray, finally! I'll integrate an updated gist and get the ball rolling on another release. Thank you for your patience!

**Comment by piercifani** [comment]
Great! do we have an ETA for beta 3?

**Comment by zwaldowski** [comment]
I'll cut it shortly!

**Comment by zwaldowski** [comment]
Sometime today, even!

**Comment by zwaldowski** [comment]
OK, merged with master… letting 👷 sign off…

**Pull request merged**
