### PR TITLE
Arguments label API fixes

### PR DESCRIPTION
**Pull request by zwaldowski**

### CODE REVIEW

**Comment by randomstep** [comment]
:+1: I like this change.

**Comment by randomstep** [comment]
Any documentation or example updates needed?

**Comment by zwaldowski** [comment]
@randomstep: No, doc comments should use the internal variable name, so it stays "transform". If we're using the full signature anywhere, i.e., `map(upon:transform:)` should become `map(upon:_:)`, so I'll do a brief look for those.

**Comment by zwaldowski** [comment]
Nope, there are none. I take it you're gonna make me merge it myself? :stuck_out_tongue:

**Pull request merged**
