### PR TITLE
Lock-free implementation

### PR DESCRIPTION
**Pull request by zwaldowski**
* Uses modern GCD features to eliminate locking
   - Significantly reduce threading overhead
   - Minor behavioral change: `fill(_:)` no longer happens synchronously.
   - Requires iOS 8. Consensus among BNR folk: we should tag a 1.0 before merging (if merging is what we want to do) for use on iOS 7 with CocoaPods/including Deferred.swift directly.
* Renames and combines several methods in the spirit of Swift 2 and the stdlib.
* A new `wait(_:)` primitive underlies both `value` and `peek()`, also allowing for block-with-timeout use.
* `any(_:)` and `all(_:)` now take any collection, such as the result of a `lazy(_:).filter(_:)` or so on.
   - `all(_:)` now uses a dispatch group for synchronization; tasks are executed in parallel.

### CODE REVIEW

**Comment by zwaldowski** [comment]
Rebased against master.

**Comment by jeremy-w** [comment]
Why not remove LockProtected.swift and its tests file?

**Comment by zwaldowski** [comment]
I did not feel the need to remove API that is currently in use;
 LockProtected has been used in every project that's used Deferred so far.

[image: Big Nerd Ranch logo] <http://www.bignerdranch.com/>

   - *Zachary Waldowski*
   - Software Developer
   - Big Nerd Ranch <http://bignerdranch.com/>
   - zachary@bignerdranch.com
   - (843) 333-6836

**Comment by jeremy-w** [comment]
It looks like dead code from the perspective of all the code remaining in Deferred. If it's effectively getting equal footing, we should maybe add some docs on it to the README as well?

**Comment by zwaldowski** [comment]
Blocked on Swift 2.0 (requiring very few changes, see 71286bcd4c) due to rdar://22437691 ([OpenRadar](http://www.openradar.me/22437691)).

**Comment by zwaldowski** [comment]
Rebased to depend on #25. Please review that one first.

**Comment by zwaldowski** [comment]
Updated to fix an API contract invalidation. No longer blocked for Swift 2; separate PR incoming.

**Comment by zwaldowski** [comment]
Closing now that all changes will be for Swift 2 (#30, #33, and #29). The Swift 1.0 version will stay as-is. Split out the discussion about `LockProtected` into #34.

**Pull request closed without merging**
