### PR TITLE
Swift 3.2 improvements

### PR DESCRIPTION
**Pull request by zwaldowski**
#### What's in this pull request?

Sets 3.2 as the syntax mode with some optimizations; continue to deploy to 3.0-4.0.

#### Testing

WIP

#### API Changes

None.

### CODE REVIEW

**Comment by piercifani** [comment]
With Xcode 9 GM ready, any ETA on this?

**Comment by zwaldowski** [comment]
We should be OK shipping this, I’ll look back into it today. I do want Travis to have the GM first, which it should soon. That being said, AFAIK nothing’s actually broken in Deferred 3.1.2 against Swift 3.2/4.0; these are quality-of-life improvements.

**Comment by piercifani** [comment]
Can we cut a release with this so I can integrate with Cocoapods more easily?

**Comment by zwaldowski** [comment]
@piercifani CocoaPods was having trouble deciding the Swift version last week. It’s pushed now! :)

**Comment by piercifani** [comment]
✈️

**Pull request merged**
